# Generated by Django 4.2.23 on 2025-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
